### ISSUE TITLE
Can't run your OSSPolice

### ISSUE THREAD

**Issue by BBIGBOSS** [osssanitizer/osspolice#1]
I managed to setup your osspolice, but still can't run anything on it. Do I have to download the repos by myself ? Because I didn't see the code of controller that manage that part and when I run command, it told me that redis is empty.

        Also, I wanted to know the specific meanings of every command under /main and what they do, it has been really confusing me even if I took a peek on your paper.

        Please give me a list of steps that I could follow to run with at least one result.

        Thanks!

**Comment by BBIGBOSS** [comment]
update: 
    Trying to index a jar repo and get Two Var not defined : JARSIGNIFY_DIR and JARSIGNIFY_JAR

**Comment by if-gh** [comment]
Same here.
@BBIGBOSS May I ask how did you get the redis cluster to work? I can only have it working on non-cluster mode due to redis-py-cluster client errors.

I believe ```os.chdir(JARSIGNIFY_DIR)``` could be change to something like ```os.chdir('java_parser/')```,  and ```JARSIGNIFY_JAR```  to ```JAVA_PARSER_JAR```, these parameters are either not set in the config, or typos.

I can now index java JAR files with ```java_index```, but ```index``` doesn't seem to work when I'm trying to index some repos, either stuck or return nothing at all, and there is no instructions at all....

**Comment by BBIGBOSS** [comment]
@YFGu0618 It's because your firewall settings. To try iptables -F on your host is the simplest way.

**Comment by BBIGBOSS** [comment]
@lingfennan In paper you said this tool can be used to index java source, did you mean java file or class file ?
